# AI Retail Intelligence ANALYTICS

# Objective: Build an end-to-end retail intelligence system using python and tableau for business analytics,customer segmentation and sales forecasting

# Import Libraries

In [1]:
import pandas as pd 
import numpy as np

# Load Dataset

In [12]:
orders = pd.read_csv(r"C:\Users\SHREE SINHA\OneDrive\Desktop\AI_Retail_Intelligence_Project\Data_raw\olist_orders_dataset.csv.zip")
items = pd.read_csv(r"C:\Users\SHREE SINHA\OneDrive\Desktop\AI_Retail_Intelligence_Project\Data_raw\olist_order_items_dataset.csv.zip")
payments = pd.read_csv(r"C:\Users\SHREE SINHA\OneDrive\Desktop\AI_Retail_Intelligence_Project\Data_raw\olist_order_payments_dataset.csv.zip")
customers = pd.read_csv(r"C:\Users\SHREE SINHA\OneDrive\Desktop\AI_Retail_Intelligence_Project\Data_raw\olist_customers_dataset.csv.zip")
products = pd.read_csv(r"C:\Users\SHREE SINHA\OneDrive\Desktop\AI_Retail_Intelligence_Project\Data_raw\olist_products_dataset.csv.zip")
translation = pd.read_csv(r"C:\Users\SHREE SINHA\OneDrive\Desktop\AI_Retail_Intelligence_Project\Data_raw\product_category_name_translation.csv")

In [8]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\shree sinha\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\shree sinha\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [15]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [16]:
translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [17]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [18]:
items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [19]:
payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [20]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [21]:
translation.columns

Index(['product_category_name', 'product_category_name_english'], dtype='object')

In [22]:
df = orders.merge(customers,on = 'customer_id')

In [23]:
df = df.merge(payments, on = 'order_id')

In [24]:
df = df.merge(items, on = 'order_id')

In [25]:
df = df.merge(products, on = 'product_id')

In [26]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,29.99,8.72,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,118.70,22.76,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,159.90,19.22,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0

# Data Cleaning

In [27]:
df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date     1245
order_delivered_customer_date    2567
order_estimated_delivery_date       0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
payment_sequential                  0
payment_type                        0
payment_installments                0
payment_value                       0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
product_category_name            1698
product_name_lenght              1698
product_description_lenght       1698
product_photos_qty               1698
product_weight_g                   20
product_length_cm                  20
product_height_cm                  20
product_width_cm                   20
dtype: int64

In [28]:
df = df.dropna()

In [29]:
df.isnull().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
customer_unique_id               0
customer_zip_code_prefix         0
customer_city                    0
customer_state                   0
payment_sequential               0
payment_type                     0
payment_installments             0
payment_value                    0
order_item_id                    0
product_id                       0
seller_id                        0
shipping_limit_date              0
price                            0
freight_value                    0
product_category_name            0
product_name_lenght              0
product_description_lenght       0
product_photos_qty               0
product_weight_g                 0
product_length_cm                0
product_height_cm                0
product_width_cm                 0
dtype: int64

In [31]:
df.shape

(113390, 30)

# Feature Engineering

In [32]:
df['Revenue'] = df['payment_value']

In [34]:
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])

In [35]:
df['Month'] = df['order_purchase_timestamp'].dt.month

In [36]:
df['Year'] = df['order_purchase_timestamp'].dt.year

In [37]:
df = df.merge(translation, on = 'product_category_name',how = 'left')

In [39]:
df.to_csv(r"C:\Users\SHREE SINHA\OneDrive\Desktop\AI_Retail_Intelligence_Project\Data_cleaned\cleaned_retail_data.csv", index = False)

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\SHREE SINHA\OneDrive\Desktop\AI_Retail_Intelligence_Project\Data_cleaned\cleaned_retail_data.csv")

In [4]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,Revenue,Month,Year,product_category_name_english
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,268.0,4.0,500.0,19.0,8.0,13.0,18.12,10,2017,housewares
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,268.0,4.0,500.0,19.0,8.0,13.0,2.00,10,2017,housewares
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,268.0,4.0,500.0,19.0,8.0,13.0,18.59,10,2017,housewares
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,178.0,1.0,400.0,19.0,13.0,19.0,141.46,7,2018,perfumery
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,232.0,1.0,420.0,24.0,19.0,21.0,179.12,8,2018,auto

In [5]:
customer_spend = df.groupby('customer_unique_id')['Revenue'].sum().reset_index()

In [6]:
customer_spend.head()

                 customer_unique_id  Revenue
0  0000366f3b9a7992bf8c76cfdf3221e2   141.90
1  0000b849f77a49e4a4ce2b2a4ca5be3f    27.19
2  0000f46a3911fa3c0805444483337064    86.22
3  0000f6ccb0745a6a4b88665a16c9f078    43.62
4  0004aac84e0df4da2b147fca70cf8255   196.89

# Customer Segmentation

In [7]:
from sklearn.cluster import KMeans

In [8]:
X = customer_spend[['Revenue']]

In [9]:
kmeans = KMeans(n_clusters = 3 , random_state = 42)

In [10]:
customer_spend['Segment'] = kmeans.fit_predict(X)

In [11]:
customer_spend.head()

                 customer_unique_id  Revenue  Segment
0  0000366f3b9a7992bf8c76cfdf3221e2   141.90        0
1  0000b849f77a49e4a4ce2b2a4ca5be3f    27.19        0
2  0000f46a3911fa3c0805444483337064    86.22        0
3  0000f6ccb0745a6a4b88665a16c9f078    43.62        0
4  0004aac84e0df4da2b147fca70cf8255   196.89        0

In [12]:
mapping = {
    0 : 'Low Value' , 
    1 : 'Medium Value' ,
    2 : 'High Value' 
}
customer_spend['Segment'] = customer_spend['Segment'].map(mapping)

In [13]:
customer_spend.head()

                 customer_unique_id  Revenue    Segment
0  0000366f3b9a7992bf8c76cfdf3221e2   141.90  Low Value
1  0000b849f77a49e4a4ce2b2a4ca5be3f    27.19  Low Value
2  0000f46a3911fa3c0805444483337064    86.22  Low Value
3  0000f6ccb0745a6a4b88665a16c9f078    43.62  Low Value
4  0004aac84e0df4da2b147fca70cf8255   196.89  Low Value

In [14]:
customer_spend.to_csv(r"C:\Users\SHREE SINHA\OneDrive\Desktop\AI_Retail_Intelligence_Project\Data_cleaned\customer_segments.csv", index = False)

In [16]:
customer_spend.groupby('Segment')['Revenue'].mean()

Segment
High Value      109312.640000
Low Value          203.525201
Medium Value     16031.205116
Name: Revenue, dtype: float64

In [17]:
customer_spend['Segment'].value_counts()

Segment
Low Value       92037
Medium Value       43
High Value          1
Name: count, dtype: int64

In [18]:
import numpy as np

In [19]:
customer_spend['Log_Revenue'] = np.log1p(
    customer_spend['Revenue']
)

In [20]:
X = customer_spend[['Log_Revenue']]

In [21]:
from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=3,
    random_state=42
)

In [22]:
customer_spend['Cluster'] = kmeans.fit_predict(X)

In [23]:
customer_spend.groupby('Cluster')['Revenue'].mean()

Cluster
0    778.920294
1     55.731549
2    159.443075
Name: Revenue, dtype: float64

In [24]:
customer_spend['Cluster'].value_counts()

Cluster
2    41441
1    36673
0    13967
Name: count, dtype: int64

In [25]:
mapping = {
    0: 'Low Value',
    1: 'Medium Value',
    2: 'High Value'
}

customer_spend['Segment'] = customer_spend[
    'Cluster'
].map(mapping)

# Export Cleaned files

In [26]:
customer_spend.to_csv(r"C:\Users\SHREE SINHA\OneDrive\Desktop\AI_Retail_Intelligence_Project\Data_cleaned\customer_segments.csv"
    ,
    index=False
)